name: Build
on:
  merge_group:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
jobs:
  build:
    runs-on: [ "self-hosted"]
    timeout-minutes: 30
    if: '! github.event.pull_request.draft'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build SampleApplication
        run: ./gradlew --no-daemon build