name: Build
on:
  merge_group:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
jobs:
  build:
    runs-on: [ "self-hosted"]
    timeout-minutes: 30
    if: '! github.event.pull_request.draft'
    steps:
      - name: Clear Android setup cache
        run: |
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_actions\android-actions\setup-android
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_temp\_runner_file_commands
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_temp\_runner_file_extracted
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_temp\zulu
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_tool\Java_Zulu_jdk
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_tool
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\tools
          rmdir /S /Q C:\Users\Flavi\actions-runner\self-hosted\_runner_tools
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup android SDK
        uses: android-actions/setup-android@v2
      - run: chmod +x gradlew
      - name: Build app
        run: ./gradlew assembleDevDebug
